AL2_0_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL2_0_ASEGeoOpt_2:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 1.0
AL2_0_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 100
    steps: 1000000
AL2_0_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_0_ASEMD_modifier_0:
    end_temperature: 450
    interval: 1
    num_oscillations: 10
    start_temperature: 270
    temperature_amplitude: 150
AL2_0_ASEMD_modifier_1:
    cell_amplitude: 1
    end_cell: null
    interval: 1
    num_oscillations: 3
AL2_0_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL2_0_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 20
    n_configurations: 20
    reference: energy
    threshold: null
AL2_0_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL2_0_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_0_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_1_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
AL2_1_ASEGeoOpt_2:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 1.0
AL2_1_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 100
    steps: 1000000
AL2_1_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_1_ASEMD_modifier_0:
    end_temperature: 450
    interval: 1
    num_oscillations: 10
    start_temperature: 270
    temperature_amplitude: 150
AL2_1_ASEMD_modifier_1:
    cell_amplitude: 1
    end_cell: null
    interval: 1
    num_oscillations: 3
AL2_1_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL2_1_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 20
    n_configurations: 20
    reference: energy
    threshold: null
AL2_1_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL2_1_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_1_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_2_ASEGeoOpt_1:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 1.0
AL2_2_ASEGeoOpt_1_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_2_ASEGeoOpt_2:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 2.0
AL2_2_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 40
    steps: 1000000
AL2_2_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_2_ASEMD_modifier_0:
    end_temperature: 450
    interval: 1
    num_oscillations: 10
    start_temperature: 270
    temperature_amplitude: 150
AL2_2_ASEMD_modifier_1:
    cell_amplitude: 1
    end_cell: 16.511
    interval: 1
    num_oscillations: 3
AL2_2_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL2_2_ConfigurationSelection_1:
    indices:
        _type: slice
        value:
            start: 10
            step: null
            stop: -1
AL2_2_ConfigurationSelection_2:
    indices:
        _type: slice
        value:
            start: 4
            step: null
            stop: -1
AL2_2_ConfigurationSelection_3:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL2_2_ConfigurationSelection_4:
    key: energy_uncertainty
    min_distance: 20
    n_configurations: 20
    reference: energy
    threshold: null
AL2_2_ConfigurationSelection_5:
    n_configurations: 5
    seed: 1234
AL2_2_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_2_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_3_ASEGeoOpt_1:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 1.0
AL2_3_ASEGeoOpt_1_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_3_ASEGeoOpt_2:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 2.0
AL2_3_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 40
    steps: 1000000
AL2_3_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_3_ASEMD_modifier_0:
    end_temperature: 450
    interval: 1
    num_oscillations: 10
    start_temperature: 270
    temperature_amplitude: 150
AL2_3_ASEMD_modifier_1:
    cell_amplitude: 1
    end_cell: 16.511
    interval: 1
    num_oscillations: 3
AL2_3_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL2_3_ConfigurationSelection_1:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL2_3_ConfigurationSelection_2:
    key: energy_uncertainty
    min_distance: 20
    n_configurations: 20
    reference: energy
    threshold: null
AL2_3_ConfigurationSelection_3:
    n_configurations: 5
    seed: 1234
AL2_3_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_3_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_4_ASEGeoOpt_1:
    data_id: -5
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 1.0
AL2_4_ASEGeoOpt_1_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_4_ASEGeoOpt_2:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 2.0
AL2_4_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 40
    steps: 1000000
AL2_4_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL2_4_ASEMD_modifier_0:
    end_temperature: 450
    interval: 1
    num_oscillations: 10
    start_temperature: 270
    temperature_amplitude: 150
AL2_4_ASEMD_modifier_1:
    cell_amplitude: 1
    end_cell: 16.511
    interval: 1
    num_oscillations: 3
AL2_4_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL2_4_ConfigurationSelection_1:
    indices:
        _type: slice
        value:
            start: 0
            step: null
            stop: -1
AL2_4_ConfigurationSelection_2:
    key: energy_uncertainty
    min_distance: 20
    n_configurations: 20
    reference: energy
    threshold: null
AL2_4_ConfigurationSelection_3:
    n_configurations: 5
    seed: 1234
AL2_4_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL2_4_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_0_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_0_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_0_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_0_BoxScale:
    data_id: -1
    num: 100
    start: 0.9
    stop: 2.0
AL_0_BoxScale_mapping:
    frozen: false
AL_0_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_0_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_0_EnergyUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_0_ForcesUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_0_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_0_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_1_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_1_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_1_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_1_BoxScale:
    data_id: -1
    num: 100
    start: 0.9
    stop: 2.0
AL_1_BoxScale_mapping:
    frozen: false
AL_1_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_1_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_1_EnergyUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_1_ForcesUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_1_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_1_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_2_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_2_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_2_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_2_BoxScale:
    data_id: -1
    num: 100
    start: 0.9
    stop: 2.0
AL_2_BoxScale_mapping:
    frozen: false
AL_2_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_2_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_2_EnergyUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_2_ForcesUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_2_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_2_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_3_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_3_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_3_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_3_BoxScale:
    data_id: -1
    num: 100
    start: 0.9
    stop: 2.0
AL_3_BoxScale_mapping:
    frozen: false
AL_3_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_3_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_3_EnergyUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_3_ForcesUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_3_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_3_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_4_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_4_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_4_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_4_BoxScale:
    data_id: -1
    num: 100
    start: 0.9
    stop: 2.0
AL_4_BoxScale_mapping:
    frozen: false
AL_4_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_4_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_4_EnergyUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_4_ForcesUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_4_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_4_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_5_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_5_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_5_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_5_BoxScale:
    data_id: -1
    num: 100
    start: 0.9
    stop: 2.0
AL_5_BoxScale_mapping:
    frozen: false
AL_5_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_5_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_5_EnergyUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_5_ForcesUncertaintyHistogram:
    bins: null
    x_lim: null
    y_lim: null
AL_5_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_5_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ASEGeoOpt:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
ConfigurationSelection:
    n_configurations: 20
    seed: 1234
Packmol:
    box: null
    count:
    - 38
    data_ids: null
    density: 1095.2
    tolerance: 2.0
SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CS(=O)C
bootstrap_0_BoxScale:
    data_id: -1
    num: 100
    start: 0.9
    stop: 2.0
bootstrap_0_BoxScale_mapping:
    frozen: false
bootstrap_0_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
bootstrap_0_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
bootstrap_0_RotateMolecules:
    data_id: -1
    include_original: false
    maximum: 0.17452777777777778
    n_configurations: 10
    seed: 1
bootstrap_0_RotateMolecules_test:
    data_id: -1
    include_original: false
    maximum: 0.17452777777777778
    n_configurations: 5
    seed: 2
bootstrap_0_TranslateMolecules:
    data_id: -1
    include_original: false
    maximum: 0.2
    n_configurations: 10
    seed: 1
bootstrap_0_TranslateMolecules_test:
    data_id: -1
    include_original: false
    maximum: 0.2
    n_configurations: 5
    seed: 2
bootstrap_1_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 100
    steps: 10000
bootstrap_1_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
bootstrap_1_ASEMD_modifier_0:
    end_temperature: 450
    interval: 1
    num_oscillations: 10
    start_temperature: 270
    temperature_amplitude: 150
bootstrap_1_ASEMD_modifier_1:
    cell_amplitude: 1
    end_cell: null
    interval: 1
    num_oscillations: 3
bootstrap_1_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
bootstrap_1_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 20
    reference: energy
    threshold: null
bootstrap_1_ConfigurationSelection_2:
    n_configurations: 80
    seed: 1234
bootstrap_1_ConfigurationSelection_3:
    n_configurations: 20
    seed: 1234
evaluation_BoxScale:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_1:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_10:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_10_mapping:
    frozen: false
evaluation_BoxScale_1_mapping:
    frozen: false
evaluation_BoxScale_2:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_2_mapping:
    frozen: false
evaluation_BoxScale_3:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_3_mapping:
    frozen: false
evaluation_BoxScale_4:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_4_mapping:
    frozen: false
evaluation_BoxScale_5:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_5_mapping:
    frozen: false
evaluation_BoxScale_6:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_6_mapping:
    frozen: false
evaluation_BoxScale_7:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_7_mapping:
    frozen: false
evaluation_BoxScale_8:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_8_mapping:
    frozen: false
evaluation_BoxScale_9:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
evaluation_BoxScale_9_mapping:
    frozen: false
evaluation_BoxScale_mapping:
    frozen: false
final_BoxScale:
    data_id: -1
    num: 100
    start: 0.9
    stop: 2.0
final_BoxScale_mapping:
    frozen: false
final_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
isolated_mol_SmilesToConformers:
    cell: 100
    maxAttempts: 1000
    numConfs: 200
    seed: 42
    smiles: CS(=O)C
volume_scan_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    steps: 250
volume_scan_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
volume_scan_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
volume_scan_BoxScale:
    data_id: -1
    num: 50
    start: 0.9
    stop: 1.7
volume_scan_BoxScale_mapping:
    frozen: false
