AL_0_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    init_velocity: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_0_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_0_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_0_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_0_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_0_EnergyUncertaintyHistogram:
    bins: null
AL_0_ForcesUncertaintyHistogram:
    bins: null
AL_0_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_0_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_1_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    init_velocity: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_1_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_1_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_1_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_1_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_1_EnergyUncertaintyHistogram:
    bins: null
AL_1_ForcesUncertaintyHistogram:
    bins: null
AL_1_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_1_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_2_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    init_velocity: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_2_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_2_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_2_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_2_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_2_EnergyUncertaintyHistogram:
    bins: null
AL_2_ForcesUncertaintyHistogram:
    bins: null
AL_2_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_2_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_3_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    init_velocity: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_3_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_3_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_3_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_3_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_3_EnergyUncertaintyHistogram:
    bins: null
AL_3_ForcesUncertaintyHistogram:
    bins: null
AL_3_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_3_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_4_ASEMD:
    data_id: -1
    dump_rate: 1000
    init_temperature: null
    init_velocity: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 50000
AL_4_ASEMD_checker_list_0:
    larger_only: true
    max_std: null
    max_value: 2.0
    minimum_window_size: 1
    value: energy_uncertainty
    window_size: 500
AL_4_ASEMD_thermostat:
    friction: 0.01
    temperature: 298.15
    time_step: 0.5
AL_4_ConfigurationSelection_1:
    key: energy_uncertainty
    min_distance: 10
    n_configurations: 10
    reference: energy
    threshold: null
AL_4_ConfigurationSelection_2:
    n_configurations: 5
    seed: 1234
AL_4_EnergyUncertaintyHistogram:
    bins: null
AL_4_ForcesUncertaintyHistogram:
    bins: null
AL_4_MLModel:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
AL_4_MLModel_1:
    jax_enable_x64: true
    use_energy: true
    use_forces: true
    use_stresses: false
ASEGeoOpt:
    data_id: 0
    dump_rate: 1000
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
ConfigurationSelection:
    n_configurations: 20
    seed: 1234
Packmol:
    box: null
    count:
    - 38
    data_ids: null
    density: 1095.2
    tolerance: 2.0
SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CS(=O)C
