callbacks:
- name: csv
checkpoints:
  base_model_checkpoint: null
  ckpt_interval: 1
  reset_layers: []
data:
  batch_size: 8
  data_path: null
  energy_unit: eV
  model_name: ''
  model_path: apax_model
  n_train: 1000
  n_valid: 100
  pos_unit: Ang
  scale_method: per_element_force_rms_scale
  scale_options: {}
  shift_method: per_element_regression_shift
  shift_options:
    energy_regularisation: 1.0
  shuffle_buffer_size: 1000
  test_data_path: null
  train_data_path: train_atoms.extxyz
  val_data_path: val_atoms.extxyz
  valid_batch_size: 80
loss:
- loss_type: structures
  name: energy
  weight: 1.0
- loss_type: structures
  name: forces
  weight: 4.0
- loss_type: structures
  name: stress
  weight: 0.2
maximize_l2_cache: false
metrics:
- name: energy
  reductions:
  - mae
- name: forces
  reductions:
  - mae
- name: stress
  reductions:
  - mae
model:
  b_init: zeros
  calc_stress: true
  descriptor_dtype: fp32
  emb_init: uniform
  n_basis: 4
  n_contr: -1
  n_radial: 3
  nn:
  - 5 #512
  - 5 #512
  r_max: 5.5
  r_min: 0.7
  readout_dtype: fp32
  scale_shift_dtype: fp32
  use_reax: false
  use_zbl: false #true
n_epochs: 2048
optimizer:
  emb_lr: 0.01
  nn_lr: 0.005
  opt_kwargs: {}
  opt_name: adam
  reax_lr: 0.001
  sam_rho: 0.0
  scale_lr: 0.001
  shift_lr: 0.05
  transition_begin: 0
  zbl_lr: 0.001
patience: 1024
progress_bar:
  disable_epoch_pbar: false
  disable_nl_pbar: false
seed: 5
